version: '3'
services:
  rust-sample:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ".:/workspace"
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_ENABLE_LAB=yes
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "${JUPYTER_PORT}:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888 --notebook-dir /workspace
